'use server';

import { getDbConnection } from '@/lib/db';
import fs from 'fs';
import path from 'path';

/**
 * Server Action to retrieve the test private key for easy local evaluation.
 * 
 * @returns {Promise<string>} Private Key PEM string or empty string if not available
 */
export async function getTestPrivateKey() {
  try {
    const keyPath = path.join(process.cwd(), 'keys', 'private.pem');
    if (fs.existsSync(keyPath)) {
      return fs.readFileSync(keyPath, 'utf8');
    }
  } catch (error) {
    console.error('Error loading test private key:', error);
  }
  return '';
}

/**
 * Server Action to retrieve the test public key for easy local evaluation.
 * 
 * @returns {Promise<string>} Public Key PEM string or empty string if not available
 */
export async function getTestPublicKey() {
  try {
    const keyPath = path.join(process.cwd(), 'keys', 'public.pem');
    if (fs.existsSync(keyPath)) {
      return fs.readFileSync(keyPath, 'utf8');
    }
  } catch (error) {
    console.error('Error loading test public key:', error);
  }
  return '';
}

/**
 * Server Action to search residents using HMAC-SHA256 hashes generated by the client.
 * Serves zero-knowledge Searchable Encryption. No keys are sent to the server.
 * 
 * @param {string} searchHash - HMAC-SHA256 hex string of the search word or query
 * @returns {Promise<{success: boolean, data?: Array, error?: string}>}
 */
export async function searchResidentsByHash(searchHash) {
  if (!searchHash || !/^[0-9a-fA-F]{64}$/.test(searchHash)) {
    return { success: true, data: [] }; // Return empty if invalid hash formatting
  }

  try {
    const db = await getDbConnection();
    const residents = await db.queryByHash(searchHash);

    // Strip indexes if they exist in returned data (safety)
    const cleanData = residents.map(({ nama_index, nik_index, ...rest }) => rest);
    return { success: true, data: cleanData };
  } catch (error) {
    console.error('Database query by hash failed:', error);
    return { success: false, error: 'Gagal melakukan query database terenkripsi.' };
  }
}
